### PR TITLE
Fix "isNo.dir" error on local deploy to symlink target

### LINKED ISSUE #108: Error when deploying to local symlink target
### Description

I have my workspace configured like this:
```
C:\Users\me\workspace
 ├ local
 │  ├ css
 │  ├ html
 │  ├ js
 │  └ ...
 └ remote [C:\remote]
    ├ css
    ├ html
    ├ js
    └ ...
```
where remote is a symbolic link (or more precisely, a directory junction, one that created with `mklink /j`) to another folder on the same machine.

Now I want to configure deploy to use the remote folder as the target. However, when I try to deploy it, the console output the following error:
```
🔥: 'isNo.dir'
```

Deploying to a test folder within the same workspace works fine.

### Actual behavior

File not deployed, console output error

### Expected behavior

File is deployed

### Steps to reproduce

1. Install Visual Studio Code and then install Deploy (Reloaded) from marketplace
2. Create a workspace folder and then open cmd to run the following commands:
```cmd
mkdir local
mkdir fake-remote
mklink /j remote fake-remote
```
3. Configure Deploy (Reloaded) with the config below
4. Create a test file in local and try deploying it

#### Example config

```json
{
    "deploy.reloaded": {
        "packages": [{
            "name": "test",
            "description": "test"
        }],
        "targets": [{
            "type": "local",
            "name": "fake-remote",
            "description": "test",
            "dir": "./remote",
            "mappings": {
                "/local/**/*": "/"
            }
        }]
    }
}
```

#### Logs

```
INFO extension.deploy.reloaded.loadplugins - [22/Dec/2018:06:25:44 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
```

### Your environment

- Operating system: Windows 10 v1803 Build 17134
- Visual Studio Code version: 1.30.1 (user setup)
- Extension version: 0.86.0

### PR DESCRIPTION
**Pull request by zypA13510**
Close #108.

### CODE REVIEW

**Comment by zypA13510** [comment]
Tested manually on my VS code 1.35.1 installed on Windows 10 x86-64.
It seems that the test script is not for testing of functionalities, so no automatic test script added.

**Comment by woodpile72** [comment]
This still isn't working.  I have a remote filesystem mounted using a fuse mount in linux.  That fs contains directories that are symlinked to another.  If I open a file from within the symlinked directory, deploy doesn't work - get the isNo.dir error.  If I open from the target directory, it works fine.

I've used it this way for years with no trouble, but just recently started using this extension with vscode.  From bash or nemo (linux mint cinnamon file manager) or anything else, it works when editing a file in either the target of the symlink dir or the symlinked dir.

What information can I provide to help?

**Comment by woodpile72** [comment]
Following up...  follow_symlinks works for ctrl-alt-f deploy, but deployonsave doesn't work.

**Comment by zypA13510** [comment]
Sorry but I don't have any SSHFS on my linux environment. To diagnose this, could you try to run this and paste the output here (replace the path with yours)?
```JavaScript
const PATH = "/path/to/symlink";
const fs = require("fs");
fs.realpath(PATH, (err, path) => {
  if (err) {
    console.log(`err: ${err}`);
  } else {
    console.log(`realpath: ${path}`);
    fs.lstat(path, (err, stats) => {
      console.log(err ? `err: ${err}` : `isDir: ${stats.isDirectory()}`);
    });
  }
});
fs.stat(PATH, (err, stats) => {
  console.log(err ? `err: ${err}` : `stat.isDir: ${stats.isDirectory()}`);
});
```
Oneliner (same as above but minified, just paste in a bash shell then run):
```
node -e 'const P="/path/to/symlink",f=require("fs"),l=console.log;f.realpath(P,(s,o)=>s?l(`err: ${s}`):(l(`realpath: ${o}`),f.lstat(o,(s,o)=>l(s?`err: ${s}`:`isDir: ${o.isDirectory()}`)))),f.stat(P,(s,o)=>l(s?`err: ${s}`:`stat.isDir: ${o.isDirectory()}`))'
```

Btw, maybe you should create a new issue first, as I cannot guarantee to find a solution for your situation and a separate issue helps track the problem.

**Comment by woodpile72** [comment]
Thanks for the attention on this!

This is for the file in question.  Expect this to fail because it's check for dir, not file.

$ node -e 'const P="/mnt/site/html/test/test.phtml",f=require("fs"),l=console.log;f.realpath(P,(s,o)=>s?l(`err: ${s}`):(l(`realpath: ${o}`),f.lstat(o,(s,o)=>l(s?`err: ${s}`:`isDir: ${o.isDirectory()}`)))),f.stat(P,(s,o)=>l(s?`err: ${s}`:`stat.isDir: ${o.isDirectory()}`))'
stat.isDir: false
realpath: /mnt/site/html/test/test.phtml
isDir: false

This is for that actual directory.

$ node -e 'const P="/mnt/site/html/test",f=require("fs"),l=console.log;f.realpath(P,(s,o)=>s?l(`err: ${s}`):(l(`realpath: ${o}`),f.lstat(o,(s,o)=>l(s?`err: ${s}`:`isDir: ${o.isDirectory()}`)))),f.stat(P,(s,o)=>l(s?`err: ${s}`:`stat.isDir: ${o.isDirectory()}`))'
stat.isDir: true
realpath: /mnt/site/html/test
isDir: true

Here, /mnt/site/html/test is a symlink ON THE REMOTE SYSTEM, not on the local system, to /mnt/site/html/sys/test

If you need anything else, please don't hesitate to ask.

**Comment by zypA13510** [comment]
`/mnt/site/html/test` is your deploy target, and if you set deploy target to `/mnt/site/html/sys/test` then it's fine?

**Comment by woodpile72** [comment]
The deploy target is /mnt/site/ and if editing a file under /mnt/site/html/test (a symlink) deploy fails.  That file exists naturally under /mnt/site/html/sys/test (the target of the symlink) and editing and deploy from there works fine.

**Comment by zypA13510** [comment]
Oh I see. Then this is the same issue as #156 I guess. This PR #139 only dealt with the situation where your deploy target is a symlink itself. In your situation, it is a subfolder which is a symlink. And it would appear to be unsupported at the moment, but I guess you'd be welcomed to contribute a fix.

**Pull request merged**
